### ISSUE TITLE
Unable to use a YAML language server with the JetBrains YAML plugin

### ISSUE THREAD

**Issue by matthewmichihara** [ballerina-platform/lsp4intellij#102]
**Description:**
I have a simple language server registered for the `yaml` extension that returns `hello world` on hover requests. This is bundled into a sample plugin.

1. If I open a YAML file in IDEA with just my sample plugin enabled, on hover I am able to see those `hello world` tooltips:
![out](https://user-images.githubusercontent.com/79073/59885636-e5fee280-9389-11e9-82bd-1a903136f1f9.gif)

2. However, if I open a YAML file in IDEA with both my sample plugin enabled *and* the JetBrains YAML plugin enabled, I see nothing when hovering over YAML text.
![out](https://user-images.githubusercontent.com/79073/59885811-90770580-938a-11e9-9ca0-61f0b0c32cf3.gif)

Stepping through with the debugger, it looks like in case 2, it's not getting past this `if` clause in `EditorEventManager#mouseMoved()` because `LanguageDocumentation.INSTANCE.allForLanguage(language).isEmpty()` is false:
<img width="902" alt="Screen Shot 2019-06-20 at 6 13 25 PM" src="https://user-images.githubusercontent.com/79073/59886009-5ce8ab00-938b-11e9-90c1-273dcd6839cb.png">

Ideally, I'd like to be able to rely on the JetBrains YAML plugin for syntax highlighting, but use the hover documentation from my sample plugin.

**Comment by NipunaRanasinghe** [comment]
Oh I see the problem.. This is because YAML plugin has already  registered a `DocumentationProvider` for YAML (As you can see as `YamlJsonSchemaDocumentationProvider`) and since our language client is designed to give priority to the language specific plugins (The reason is that in most of the times specific plugins are more powerful than the their language servers at the moment.)  this is kind of expected :/  

One solution I see is you can override the `mouseMoved` event  by extending the `DefaultEditorEventManager` and proving it through `LSPExtensionManager` (Unfortunately we are still working on the documentation of our "client extendability" ). If you need and example for it, you can refer this ballerinaExtensionManager implementation.
 https://github.com/ballerina-platform/ballerina-lang/blob/master/tool-plugins/intellij/src/main/java/io/ballerina/plugins/idea/extensions/BallerinaLSPExtensionManager.java

Please feel free to reach out if there is anything not clear :)

**Comment by matthewmichihara** [comment]
I see, that makes sense, thanks for the explanation! Since this is working as expected, I'll go ahead and close this.
