### ISSUE TITLE
Is it possible to pass an env to LSP?

### ISSUE THREAD

**Issue by Chandlercjy** [ballerina-platform/lsp4intellij#110]
**Description:**
Is it possible to pass an env to LSP?

For example,
when starting clangd, I want to specify a CPATH for it.
I tried to send RawCommandServerDefinition like this:
```java
        RawCommandServerDefinition cpp = new RawCommandServerDefinition("cpp", new String[]{"set CPATH=xxxxx","&&","D:\\Program Files\\LLVM\\bin\\clangd.exe","-log=verbose"});
```
but it will not recognize the `set` command.

Do you have any other suggestion?
Thank you!

**Suggested Labels:**
Feature

**Comment by nixel2007** [comment]
Try `cmd /C` surrounding.

**Comment by Chandlercjy** [comment]
Sorry I don't understand.  Could you elaborate?

**Comment by dinvlad** [comment]
Same issue here. We'd like to be able to set PATH for the server process. Since the server process inherits the environment from the plugin Java process, the only ways to set the environment currently seem to be:

1) modify PATH of the IntelliJ plugin process itself. Is there a standard way to do that, other than modifying the IntelliJ launcher?

2) create a wrapper script for the server as suggested by @nixel2007, and call that script instead of the server. This has a disadvantage of having to create a potentially non-portable wrapper around the server executable (and having to distribute that wrapper in addition to the server executable).

3) modify the server itself, which is only good if we have control over that executable.

What would be helpful instead is to be able to pass a `Map<String, String> env` into `ProcessBuilder` used by `org.wso2.lsp4intellij.client.connection.ProcessStreamConnectionProvider`. This way, we could programmatically set any environmental variables for the child without having to modify any other code.

**Comment by Chandlercjy** [comment]
Agreed. For now, I will use a wrapper script.

**Comment by NipunaRanasinghe** [comment]
Hey folks! Forgive me for not being around for a while :/ It's been a hell of a month with our language release. I see your valid requirement so will add this to our task list and make this available with the next release :)

**Comment by NipunaRanasinghe** [comment]
@gayanper @nixel2007 @Chandlercjy @dinvlad I appreciate your suggestions on the $subject.

I thought of adding support for creating and passing custom `ProcessBuilder` instances via a new type of language server definition type as follows.
```
new ProcessServerDefinition(String ext,  ProcessBuilder processBuilder);
```

So this change will not break the existing API (`CommandServerDefinition`) and the user will have the full accessibility for the process to be created. WDYT?

**Comment by gayanper** [comment]
What are the use cases that we are trying to cover with this new definition ?

**Comment by NipunaRanasinghe** [comment]
@gayanper one of the critical requirements is being already discussed here(modifying the env parameters) :) So I thought of exposing the process directly to the user so that they can have more controllability over their language server process.

**Comment by gayanper** [comment]
I think its a valid point. Specially when start non java based language servers. +1 from my side for this change

**Comment by NipunaRanasinghe** [comment]
Great!

So we can either
1. replace the `RawCommandServerDefinition` with the new API, or
2. add the `ProcessServerDefinition` in addition to the `RawCommandServerDefinition` option.

IMO would be better since then this change will not break the existing lang-client based user implementations. WDYT?

**Comment by gayanper** [comment]
What if we introduce a new co structure with processbuilder and change our internal implementation to use it. We can keep the existing constructors and convert the command array to a process builder. WDYT ?

**Comment by nixel2007** [comment]
> So we can either...

also we could add overrided constructor to existing one.

**Comment by NipunaRanasinghe** [comment]
@gayanper @nixel2007  Yeah of course we can! My only concern is, would it be okay to have a user API such as ```RawCommandServerDefinition(string ext, ProcessBuilder process)```? IMO it would be better to have a new type of server definition for this, since the input won't be a `raw command` anymore. Or else we can think of an common definition name with overloaded constructors to accept either a command or a process builder instance.

**Comment by nixel2007** [comment]
>  since the input won't be a "raw command" anymore.

Agreed. 

abstract thought - looks like API has "overloaded" org/wso2/lsp4intellij/client/languageserver/serverdefinition package. So much server definition types and ways to define LS connection. do we REALLY need it?

**Comment by NipunaRanasinghe** [comment]
@nixel2007 That's a good question! These server definition types are inspired by the gtache's original implementation, but it seems command based server Definitions would be sufficient for now. So maybe we can get rid of the rest by revamping the server definition implementation, which will require a careful revamping process to avoid regressions.
