### ISSUE TITLE
jar-File unavailable 

### ISSUE THREAD

**Issue by DanielFGA** [ballerina-platform/lsp4intellij#21]
**Describe the bug**
The jar-file is unavailable.

**To Reproduce**
I tried to get the library via gradle and mvnrepository, but I couldn't get it.
With gradle I just get the flexmark-Libraries. On mvnrepository is no jar available.

**Screenshots**
![image](https://user-images.githubusercontent.com/38460699/55079658-e5152800-509c-11e9-964f-1b3972fbb86a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by nixel2007** [comment]
did you add a jipack repository to gradle?

**Comment by DanielFGA** [comment]
Yes, I tried this with the latest version, but I think there is some issue in the build:
![image](https://user-images.githubusercontent.com/38460699/55085236-a2f0e400-50a6-11e9-9426-98e8c9added3.png)

But I found out that it works with version 0.1.0.

**Comment by nixel2007** [comment]
0.1.1 can't be build on jitpack. use commits' or branches' build, or wait for next release :)

**Comment by NipunaRanasinghe** [comment]
Hi @DanielFGA! First of all, thanks for your interest!

Unfortunately we had to remove the artifacts from maven central since we had few concerns regarding the copyrights. Still you can use jitpack (0.1.1 seems to be not supported though) and If you want to try out the latest stable build I'd suggest you to use
`com.github.NipunaRanasinghe:lsp4intellij:master-0.1.1-g4210c6a-17` as your gradle dependency.

I'm bit busy with few other works these days but will try do the next release within next few days :)

**Comment by DanielFGA** [comment]
Thank you for your responses!
I will use 0.1.0 for testing and looking forward to the next release.

**Comment by NipunaRanasinghe** [comment]
@DanielFGA We have released the version 0.8.0, which has stable artifacts in jitpack :) So If you have sometime, please give it a try.

**Comment by DanielFGA** [comment]
@NipunaRanasinghe thank you 👍  I added it to my plugin and it works very fine.
