### ISSUE TITLE
[question] How to add support for none LSP methods

### ISSUE THREAD

**Issue by gayanper** [ballerina-platform/lsp4intellij#26]
I'm trying to implement STS4 idea plugin with this LSP client. in STS4 they have some custom methods on their language server, 

https://github.com/spring-projects/sts4/blob/master/idea-extensions/idea-boot-java/src/org/spring/tools/boot/java/ls/StsServerDefinition.scala

https://github.com/spring-projects/sts4/blob/master/idea-extensions/idea-boot-java/src/org/spring/tools/boot/java/ls/StsLanguageClientImpl.scala

I think i can do the same overriding mechanism as they have done with the old LSP client. But is there a better way of doing this in this new plugin ?

**Comment by NipunaRanasinghe** [comment]
Thanks for bringing this up! Actually I'm still thinking ways to improve lsp4intellij client library API to support custom language server extensions as you've mentioned above. 

I've already done a POC in https://github.com/NipunaRanasinghe/lsp4intellij-plugin/tree/master since ballerina language server also has few non LSP methods. But this is not build-able ATM, since not updated with the latest client API changes. 

Will get back to you with a solid way :)

**Comment by NipunaRanasinghe** [comment]
@gayanper @nixel2007 Please check https://github.com/ballerina-platform/lsp4intellij/issues/46#issuecomment-483495679 .

**Comment by gayanper** [comment]
@NipunaRanasinghe shall close this as well since it is now supported by https://github.com/ballerina-platform/lsp4intellij/pull/52

**Comment by NipunaRanasinghe** [comment]
@gayanper Yeah we can close this now I guess :)
